import { TypeOrmModuleOptions } from '@nestjs/typeorm';
import { ConfigService } from '@nestjs/config';
import { DataSource } from 'typeorm';
import * as dotenv from 'dotenv';
import {
  Center,
  User,
  Role,
  Lead,
  LeadTrailLesson,
  Group,
  Payment,
  TeacherSalary,
  Attendance,
  SubscriptionPlan,
  Subscription,
  Invoice,
  IeltsTest,
  IeltsListening,
  IeltsListeningPart,
  IeltsReading,
  IeltsReadingPart,
  IeltsWriting,
  IeltsWritingTask,
  IeltsQuestion,
  IeltsAudio,
  Session,
  TokenBlacklist,
  StudentAssignedTest,
  Media,
} from '../entities';

dotenv.config();

export const getDatabaseConfig = (
  configService: ConfigService,
): TypeOrmModuleOptions => ({
  type: 'mysql',
  host: configService.get<string>('DB_HOST', 'localhost'),
  port: configService.get<number>('DB_PORT', 3306),
  username: configService.get<string>('DB_USER', 'root'),
  password: configService.get<string>('DB_PASSWORD', ''),
  database: configService.get<string>('DB_NAME', 'crm_platform'),
  entities: [
    Center,
    User,
    Role,
    Lead,
    LeadTrailLesson,
    Group,
    Payment,
    TeacherSalary,
    Attendance,
    SubscriptionPlan,
    Subscription,
    Invoice,
    IeltsTest,
    IeltsListening,
    IeltsListeningPart,
    IeltsReading,
    IeltsReadingPart,
    IeltsWriting,
    IeltsWritingTask,
    IeltsQuestion,
    IeltsAudio,
    Session,
    TokenBlacklist,
    StudentAssignedTest,
    Media,
  ],
  synchronize: configService.get<string>('NODE_ENV') === 'development',
  logging: configService.get<string>('NODE_ENV') === 'development',
});

// DataSource for TypeORM CLI
export default new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '3306'),
  username: process.env.DB_USER || 'root',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || 'crm_platform',
  entities: [
    Center,
    User,
    Role,
    Lead,
    LeadTrailLesson,
    Group,
    Payment,
    TeacherSalary,
    Attendance,
    SubscriptionPlan,
    Subscription,
    Invoice,
    IeltsTest,
    IeltsListening,
    IeltsListeningPart,
    IeltsReading,
    IeltsReadingPart,
    IeltsWriting,
    IeltsWritingTask,
    IeltsQuestion,
    IeltsAudio,
    Session,
    TokenBlacklist,
    StudentAssignedTest,
    Media,
  ],
  migrations: ['src/migrations/*.ts'],
  synchronize: false,
  logging: process.env.NODE_ENV === 'development',
});
